version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - depguard
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    revive:
      rules:
        - name: comment-spacings
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/groq
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
