#!/usr/bin/env bash
#MISE description="Run unit tests"

set -euo pipefail

#USAGE arg "[pathspec]" help="Pathspec (packages/files) to format" default="./..."

go test -tags=integration -timeout=5m "${usage_pathspec:-./...}"
